package lawpro.data;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import common.models.ResponseModel;
import lawpro.repository.IUserFormRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = "userForms")
public class UserForm extends ResponseModel {

    @Autowired
    @DynamoDBIgnore
    private IUserFormRepository repo;

    @DynamoDBHashKey
    private String id;
    private String userName;
    private String formName;
    private String formData;
    private String lastModified;

    public String getId()
    {
        return id;
    }

    public void setId(String value)
    {
        id = value;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getFormName() {
        return formName;
    }

    public void setFormName(String formName) {
        this.formName = formName;
    }

    public String getFormData() {
        return formData;
    }

    public void setFormData(String formData) {
        this.formData = formData;
    }

    public String getLastModified() {
        return lastModified;
    }

    public void setLastModified(String lastModified) {
        this.lastModified = lastModified;
    }
}


