package lawpro.data;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lawpro.repository.ILookupValuesRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;

import java.util.List;

@DynamoDBTable(tableName = "lookups")
public class Lookup {

    @Autowired
    private ILookupValuesRepository repo;

    @DynamoDBHashKey
    private String id;

    private String name;

    @Transient
    @DynamoDBIgnore
    private List<LookupValue> lookups;

    @Transient
    @DynamoDBIgnore
    public List<LookupValue> getLookups() {
        return lookups;
    }

    @Transient
    @DynamoDBIgnore
    public void setLookups(List<LookupValue> lookups) {
        this.lookups = lookups;
    }

    public String getId() {
        return id.toString();
    }

    public void setId(String value) { id = value; }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    private String oldId;

    public String getOldId() {
        return oldId;
    }

    public void setOldId(String oldId) {
        this.oldId = oldId;
    }

}


